version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./deploy-conf/Dockerfile
    restart: always
    image: cognition-backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    
  nginx:
    depends_on:
      - backend
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/frontend/browser/:/var/www/frontend/
